dictionary updates
nflverse/nflreadr pull request #94
Opened 2022-03-19 18:14 UTC by pranavrajaram

2022-03-19 18:31 UTC, tanho63 requested changes
Looks OK by me! Can you add a NEWS update, bump DESCRIPTION version, and add yourself as a ctb?

2022-03-19 18:43 UTC, tanho63 requested changes

2022-03-19 18:43 UTC, tanho63 commented on data-raw/dictionary_schedules.csv
> +over_odd,numeric,Odds that total score of game would be over the total_ine.
A couple of notes for dictionary_schedules:
```r
R> load_schedules() |>
+++  dict_check(dictionary_schedules)
`old[1:3]`:               "away_coach" "away_moneyline" "away_qb_id"
`new[1:4]`: "alt_game_id" "away_coach" "away_moneyline" "away_qb_id"

     old             | new                 
[23] "home_team"     | "home_team"     [24]
[24] "location"      | "location"      [25]
[25] "nfl_detail_id" | "nfl_detail_id" [26]
[26] "old_game_id"   - "over_odd"      [27]
[27] "over_odds"     -                     
[28] "overtime"      | "overtime"      [28]
[29] "pff"           | "pff"           [29]
[30] "pfr"           | "pfr"           [30]
```
looks like `over_odd` is actually `over_odds` in the data, and there's an "old_game_id" column somewhere that i'm not sure if you've added in the actual dictionary

2022-03-19 18:43 UTC, tanho63 commented on data-raw/dictionary_schedules.csv
> +over_odd,numeric,Odds that total score of game would be over the total_ine.
Also, can you add a `%>% dplyr::mutate_all(stringr::str_squish())` to the data-raw/build_dictionaries for schedules so that any leading/trailing whitespace is eliminated? Actually this would be good for every dataframe there, just copy it through and rerun top to bottom

2022-03-19 22:49 UTC, pranavrajaram commented on data-raw/dictionary_schedules.csv
> +over_odd,numeric,Odds that total score of game would be over the total_ine.
thanks for all your help! let me know if i did anything wrong.

2022-03-20 00:46 UTC, tanho63 commented on data-raw/dictionary_schedules.csv
> +over_odd,numeric,Odds that total score of game would be over the total_ine.
no worries, i got back and made a few tweaks to what you sent over but nbd

2022-03-20 00:48 UTC, tanho63 approved these changes
LGTM - thanks!

2022-03-20 00:54 UTC, merged